#!/bin/bash

curl -X GET "https://api.hitbtc.com/api/1/public/BTCUSD/trades\?sort\=desc\&from\=0\&max_results\=1\&by\=trade_id\&start_index\=0" > /Users/ditoyp/Playground/neural_funding/data/$(date +%s).json
